### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [TeamMidnightDust/BetterBeds#11]
I was wondering if you could add support for 1.19.3? Currently the bed appears as pink and black

**Comment by Aces-and-Jacks** [comment]
I know you said you don't plan on adding to this mod anymore but its still really good when paired with enhanced block entities

**Comment by Aces-and-Jacks** [comment]
Plus it's the only mod I know that affects bed textures and optimizes rendering of beds. EBE optimizes beds but I can't get textures to work with beds

**Comment by Slooshie1** [comment]
Pull request #13 works on 1.19.3. Here is the compiled version of it: 
[betterbeds-mc1.19.3-v1.3.0.zip](https://github.com/TeamMidnightDust/BetterBeds/files/10352306/betterbeds-mc1.19.3-v1.3.0.zip)

**Comment by Aces-and-Jacks** [comment]
thanks

**Comment by Motschen** [comment]
1.3.0 is now out on CurseForge and Modrinth
