### ISSUE TITLE
No bed texture on 1.19.3

### ISSUE THREAD

**Issue by Jaec0b** [TeamMidnightDust/BetterBeds#12]
The issue is that all the beds have no texture with this mod.
It occurs whether or not you have any of the BetterBeds resource packs selected...
Game version: 1.19.3
Mod version: 1.2.0
A screenshot: [https://i.ibb.co/xmKyjSx/Screenshot-29.png](https://i.ibb.co/xmKyjSx/Screenshot-29.png)

**Comment by giorov** [comment]
Yeah, same problem, thanks!

**Comment by Motschen** [comment]
This is because of changes in vanilla that make block models unable to use entity textures.
Should be pretty easy to fix, I'll look into it.

**Comment by Slooshie1** [comment]
compiled version of #13 which works on 1.19.3: 
[betterbeds-mc1.19.3-v1.3.0.zip](https://github.com/TeamMidnightDust/BetterBeds/files/10352313/betterbeds-mc1.19.3-v1.3.0.zip)

**Comment by Motschen** [comment]
Just pushed out the 1.19.3 update on Modrinth and CurseForge, sorry for the delay.
