### ISSUE TITLE
Beds orientation broken

### ISSUE THREAD

**Issue by Wayturns** [TeamMidnightDust/BetterBeds#22]
2 ends of the bed are rotated the oposite meaning that front and back of the bed are in the middle
![image](https://github.com/TeamMidnightDust/BetterBeds/assets/92233613/37d3fe88-6eda-4258-911f-cbdf00aadc68)
latest mod vers
1.20.1

**Comment by Yoni664** [comment]
+1

**Comment by Motschen** [comment]
This is caused by also having the mod 'Enhanced Block Entities' installed. Disable the Bed features in it's config.

**Comment by MiffenKop** [comment]
> This is caused by also having the mod 'Enhanced Block Entities' installed. Disable the Bed features in it's config.

![2023-11-21_19 58 07](https://github.com/TeamMidnightDust/BetterBeds/assets/102834924/fe88a9a1-3c3e-41c7-9d9d-1eb2cfe0a61e)
![2023-11-21_19 57 20](https://github.com/TeamMidnightDust/BetterBeds/assets/102834924/121f5d07-9d34-4683-ac72-292478ca017b)

btw it still broken even when it's off

**Comment by Quetzalis** [comment]
I know it's been a long time since your post but I wanted to know if the solution has been found. I've had the mod for a while and it randomly started to do the same thing on 1.21.
