### ISSUE TITLE
1.18.2 Update Request

### ISSUE THREAD

**Issue by Obscure2020** [TeamMidnightDust/BetterBeds#7]
Hey, this is not so much a bug as a small update request.

I'm happy to report that the mod still works in 1.18.2! I've been using it for a long time and I appreciate what it does.
There's just one minor inconvenience: the resource packs the mod generates are technically an older format.

![image](https://user-images.githubusercontent.com/69320464/159143038-aa0e3e39-e83a-4784-b3e2-ad86fdb51676.png)

The game still understands the packs, and the mod does work. However, the out-of-date-ness makes some people a little worried to install it, and makes others worried that the mod might stop working at some point.

Could you possibly update it to 1.18.2?

**Comment by PweSol** [comment]
I don't have this issue on 1.18.2. However, I do have it on 1.18.1.

**Comment by Obscure2020** [comment]
That's peculiar. I definitely have this bug in 1.18.2. Just made a new instance to check.
![image](https://user-images.githubusercontent.com/69320464/159721167-c5dc422a-9230-4e82-ba6d-a4a4b2377dc7.png)

I made the testing instance with the latest versions of what's necessary to make it run. Could you make sure you're using the latest versions of all the following and try it again?
1. Minecraft `1.18.2`
2. Fabric `0.13.3`
3. Fabric API `0.48.0+1.18.2`
4. Better Beds `1.2.0`

**Comment by Obscure2020** [comment]
This issue is no longer relevant to me because I no longer use BetterBeds.
I now use Enhanced Block Entities. I have uninstalled BetterBeds.
